<?php

declare(strict_types=1);

namespace IfCastle\AQL\Entity\Property;

use IfCastle\AQL\Entity\EntityDescriptorInterface;
use IfCastle\AQL\Entity\EntityInterface;
use IfCastle\AQL\Entity\Exceptions\EntityDescriptorException;
use IfCastle\AQL\Entity\Key\KeyInterface;
use IfCastle\AQL\Executor\Context\PropertyContextInterface;

/**
 * Describes a property that consists of two or more physical database columns.
 * The class is used to describe paired keys.
 */
class ComplexProperty extends PropertyAbstract
{
    /**
     * @throws EntityDescriptorException
     */
    public static function describeReferenceByKey(
        KeyInterface                              $toKey,
        EntityInterface&EntityDescriptorInterface $toEntity,
        EntityInterface&EntityDescriptorInterface $fromEntity,
        string                                    $relationType,
        bool                                      $isRequired = true,
        ?string                                    $propertyName = null
    ): void {
        $primaryKey                 = $toEntity->getPrimaryKey();
        $namingStrategy             = $toEntity->getNamingStrategy();

        if ($primaryKey->isKeySimple()) {
            $fromEntity->describeProperty(
                $toEntity->getProperty($primaryKey->getKeyName())
                           ->cloneAsReference($toEntity->getEntityName())
                           ->setName($propertyName ?? $namingStrategy->generatePropertyName([$toEntity->getEntityName(), $primaryKey->getKeyName()], $toEntity))
                           ->setFieldName($namingStrategy->generateColumnName([$toEntity->getEntityName(), $primaryKey->getKeyName()], $toEntity))
                           ->setRelationType($relationType)
                           ->setIsNotNull($isRequired)
            );

            return;
        }

        $properties                 = [];

        foreach ($toKey->getKeyColumns() as $column) {
            $property               = $toEntity->getProperty($column);
            $properties[]           = $property;
            $fromEntity->describeProperty($property->cloneAsReference($fromEntity->getEntityName())->setIsNotNull($isRequired));
        }

        $fromEntity->describeProperty(
            (new self(
                $propertyName ?? $namingStrategy->generatePropertyName([$toEntity->getEntityName(), ...$toKey->getKeyColumns()], $toEntity),
                $toEntity->getEntityName(),
                ...$properties
            ))->setRelationType($relationType)
        );
    }

    protected bool $isVirtual       = true;

    public readonly array $properties;

    public function __construct(string $name, string $referenceToEntity, PropertyInterface ...$properties)
    {
        parent::__construct($name, self::T_TUPLE);
        $this->setReferenceToEntity($referenceToEntity);

        $this->properties           = $properties;
    }

    #[\Override]
    protected function handleBefore(PropertyContextInterface $context, string $contextName): void
    {
        parent::handleBefore($context, $contextName); // TODO: Change the autogenerated stub
    }
}
